version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_123456
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - /mnt/database/db_data:/var/lib/postgresql/data

  proxy:
    build:
      context: nginx-conf
      dockerfile: Dockerfile
    image: ghcr.io/valdemarceccon/proxy:0.2.2-alpha1
    ports:
      - "80:80"
      - "8080:8080"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    image: ghcr.io/valdemarceccon/prod-your-frontend:0.2.2-alpha1
    environment:
      BACKEND_PRIVATE_HOST: backend:8000
      ORIGIN: https://demo.valdemar.dev
      HOST: 0.0.0.0
      PORT: 3000

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.api
    image: ghcr.io/valdemarceccon/prod-your-backend-python:0.2.2-alpha1
    command: ["uvicorn", "src.server:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_123456
      POSTGRES_HOST: db
      POSTGRES_DB: dev
      POSTGRES_URL: postgresql://dev:dev_123456@db/dev
      JWT_SECRET_KEY: your-secret-key
      JWT_ALGORITHM: HS256
      BASE_PATH: /api
    user: "1000:1000"
    ports:
      - 8000:8000

  daemon:
    build:
      context: backend
      dockerfile: Dockerfile.daemon
    image: ghcr.io/valdemarceccon/prod-your-daemon-python:0.2.2-alpha1
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_123456
      POSTGRES_HOST: db
      POSTGRES_DB: dev
      POSTGRES_URL: postgresql://dev:dev_123456@db/dev
      JWT_SECRET_KEY: your-secret-key
      JWT_ALGORITHM: HS256
    volumes:
      - ./backend/daemon:/app/daemon
