version: "3.8"

services:
  db:
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_123456
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - /mnt/database/db_data:/var/lib/postgresql/data

  proxy:
    image: ghcr.io/valdemarceccon/proxy:latest
    ports:
      - "80:80"
      - "8080:8080"

  frontend:
    restart: always
    image: ghcr.io/valdemarceccon/frontend:latest
    environment:
      BACKEND_PRIVATE_HOST: backend:8000
      ORIGIN: https://demo.valdemar.dev
      HOST: 0.0.0.0
      PORT: 3000

  backend:
    restart: always
    image: ghcr.io/valdemarceccon/backend:latest
    depends_on:
      - db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_123456
      POSTGRES_HOST: db
      POSTGRES_DB: dev
      POSTGRES_URL: postgresql://dev:dev_123456@db/dev
      ENABLE_MIGRATIONS: false
    user: "1000:1000"
    ports:
      - 8000:8000

  daemon:
    restart: always
    image: ghcr.io/valdemarceccon/daemon:latest
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_123456
      POSTGRES_HOST: db
      POSTGRES_DB: dev
      POSTGRES_URL: postgresql://dev:dev_123456@db/dev
      JWT_SECRET_KEY: your-secret-key
      JWT_ALGORITHM: HS256
    volumes:
      - ./backend/daemon:/app/daemon
