@host=http://localhost/api
@user=valdemar
@email=valdemar.ceccon@gmail.com
@fullname=Valdemar Ceccon

@pass=123456
@superuser=superuser
@superpass=superpass

### register
# @name registerUser
@usertoken = {{registerUser.response.body.token}}
POST {{host}}/auth/register
Content-Type: application/json

{"username": "{{user}}",	"email": "{{email}}",	"password": "{{pass}}",	"fullname": "{{fullname}}"}

### login
# @name loginRequest
@usertoken = {{loginRequest.response.body.token}}
POST {{host}}/auth/login
Content-Type: application/json

{"username": "{{user}}", "password": "{{pass}}"}

### protected endpoint
GET {{host}}/protected-hello
Authorization: Bearer {{usertoken}}

### protected endpoint
GET {{host}}/user
Authorization: Bearer {{usertoken}}
