POST http://localhost/api/auth/signup
accept: application/json
Content-Type: application/json

{
  "email": "valdemar.ceccon3@gmail.com",
  "password": "123456",
  "name": "Valdemar Ceccon",
  "username": "valdemar.ceccon3"
}

###
POST http://localhost/api/auth/signup
accept: application/json
Content-Type: application/json

{
  "email": "valdemar.ceccon1@gmail.com",
  "password": "123456",
  "name": "Valdemar Ceccon 1",
  "username": "valdemar.ceccon1"
}

###

GET http://localhost/api/users/me
accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidGltZXN0YW1wIjoiMjAyMy0wNC0yNFQxNzo0MTo0MC4xMDcwMzAifQ.xpc_whlwRe8C6eFVhNc-lZnTSFbdzncsF3Z4YXt9hhA


###

POST http://localhost/api/auth/token
accept: application/json
Content-Type: application/json

{
  "username": "valdemar.ceccon",
  "password": "123456"
}

###
GET http://localhost/api/users
accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGltZXN0YW1wIjoiMjAyMy0wNC0yM1QyMzozNTowMS4wMzQ1MjQifQ.uA0i03BaG95VRUEGtJvTeE0ojVr0EwzfKg0-X6YU6SM

###
GET http://localhost/api/users/1
accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGltZXN0YW1wIjoiMjAyMy0wNC0yM1QyMzozNTowMS4wMzQ1MjQifQ.uA0i03BaG95VRUEGtJvTeE0ojVr0EwzfKg0-X6YU6SM
###
PATCH http://localhost/api/users/
accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGltZXN0YW1wIjoiMjAyMy0wNC0yM1QyMzozNTowMS4wMzQ1MjQifQ.uA0i03BaG95VRUEGtJvTeE0ojVr0EwzfKg0-X6YU6SM

{
  "email": "valdemar.ceccon@gmail.com",
  "password": "123456",
  "name": "Valdemar Ceccon"
}

###
POST http://localhost/api/users/api_key
accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidGltZXN0YW1wIjoiMjAyMy0wNC0yNVQyMTo0OTowNy4wMzc0NjgifQ.B-8QUmdeVH2DZTkIQhIPZFCc4jAe1wp1WRQPVyO2Ueg

{
  "name": "teste",
  "api_key": "abobrinha",
  "api_secret": "abobrinha",
  "exchange": "bybit"
}

###
GET http://localhost/api/users/api_keys/all
accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGltZXN0YW1wIjoiMjAyMy0wNC0yNlQwMToxMzo0OC4xMTA2MjEifQ.9CqzTNvfBW7QVrbZYNq_98CvWKpRlYitP1l6pV8RN_Y


###
GET http://localhost/api/users/api_keys/
accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidGltZXN0YW1wIjoiMjAyMy0wNC0yNVQyMTo0OTowNy4wMzc0NjgifQ.B-8QUmdeVH2DZTkIQhIPZFCc4jAe1wp1WRQPVyO2Ueg



###
GET http://localhost/api/users/api_key/14
accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidGltZXN0YW1wIjoiMjAyMy0wNC0yNVQyMTo0OTowNy4wMzc0NjgifQ.B-8QUmdeVH2DZTkIQhIPZFCc4jAe1wp1WRQPVyO2Ueg

###
DELETE http://localhost/api/users/api_key/6
accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGltZXN0YW1wIjoiMjAyMy0wNC0yM1QyMzozNTowMS4wMzQ1MjQifQ.uA0i03BaG95VRUEGtJvTeE0ojVr0EwzfKg0-X6YU6SM

###
PATCH http://localhost/api/users/api_key/19
accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGltZXN0YW1wIjoiMjAyMy0wNC0yNFQwMzoyNzowNS40NDE0MDIifQ.1HpyVMV_sMWPyxak6NWV-h_Z5C0Om9HCLQXvD-ibnOI

{
  "status": 2
}
