"""change api key fields

Revision ID: 425ca91a482a
Revises: 92fa26954ea9
Create Date: 2023-04-24 00:35:52.831320

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "425ca91a482a"
down_revision = "92fa26954ea9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("exchange", sa.String(length=255), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("secret", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_key_id"), "api_key", ["id"], unique=False)
    op.drop_index("ix_apikeys_id", table_name="apikeys")
    op.drop_table("apikeys")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apikeys",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "exchange", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "api_key", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "secret", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="apikeys_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="apikeys_pkey"),
    )
    op.create_index("ix_apikeys_id", "apikeys", ["id"], unique=False)
    op.drop_index(op.f("ix_api_key_id"), table_name="api_key")
    op.drop_table("api_key")
    # ### end Alembic commands ###
