"""Remove unsued column

Revision ID: 9454644cac93
Revises: 8c13cfbad613
Create Date: 2023-04-17 18:24:46.386783

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9454644cac93"
down_revision = "8c13cfbad613"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_roles_fkey", "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key("users_roles_fkey", "users", "roles", ["role_id"], ["id"])
    # ### end Alembic commands ###
