"""closed-pnl-table

Revision ID: 79fa0513bde2
Revises: b784c55b243c
Create Date: 2023-04-24 05:12:16.599091

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "79fa0513bde2"
down_revision = "b784c55b243c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "closed_pnl",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("orderId", sa.String(length=100), nullable=False),
        sa.Column("side", sa.String(length=100), nullable=False),
        sa.Column("qty", sa.String(length=100), nullable=False),
        sa.Column("orderPrice", sa.String(length=100), nullable=False),
        sa.Column("orderType", sa.String(length=100), nullable=False),
        sa.Column("execType", sa.String(length=100), nullable=False),
        sa.Column("closedSize", sa.String(length=100), nullable=False),
        sa.Column("cumEntryValue", sa.String(length=100), nullable=False),
        sa.Column("avgEntryPrice", sa.String(length=100), nullable=False),
        sa.Column("cumExitValue", sa.String(length=100), nullable=False),
        sa.Column("avgExitPrice", sa.String(length=100), nullable=False),
        sa.Column("closedPnl", sa.String(length=100), nullable=False),
        sa.Column("fillCount", sa.String(length=100), nullable=False),
        sa.Column("leverage", sa.String(length=100), nullable=False),
        sa.Column("createdTime", sa.String(length=100), nullable=False),
        sa.Column("updatedTime", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_key.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_closed_pnl_api_key_id"), "closed_pnl", ["api_key_id"], unique=False
    )
    op.create_index(op.f("ix_closed_pnl_id"), "closed_pnl", ["id"], unique=False)
    op.create_index(
        op.f("ix_closed_pnl_user_id"), "closed_pnl", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_closed_pnl_user_id"), table_name="closed_pnl")
    op.drop_index(op.f("ix_closed_pnl_id"), table_name="closed_pnl")
    op.drop_index(op.f("ix_closed_pnl_api_key_id"), table_name="closed_pnl")
    op.drop_table("closed_pnl")
    # ### end Alembic commands ###
