"""apikey-status

Revision ID: b784c55b243c
Revises: 425ca91a482a
Create Date: 2023-04-24 03:25:37.810669

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b784c55b243c"
down_revision = "425ca91a482a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_key", sa.Column("status", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_api_key_user_id"), "api_key", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_key_user_id"), table_name="api_key")
    op.drop_column("api_key", "status")
    # ### end Alembic commands ###
