"""Creates user role

Revision ID: 7f30c5d05cd8
Revises: 7ce2a5703dad
Create Date: 2023-04-17 14:42:21.332353

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7f30c5d05cd8"
down_revision = "7ce2a5703dad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
