"""Change rele desc to name

Revision ID: c1915f90ffa7
Revises: 7f30c5d05cd8
Create Date: 2023-04-17 15:00:41.734175

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c1915f90ffa7"
down_revision = "7f30c5d05cd8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_role", sa.Column("name", sa.String(), nullable=False))
    op.drop_index("ix_users_role_desc", table_name="users_role")
    op.create_index(op.f("ix_users_role_name"), "users_role", ["name"], unique=False)
    op.drop_column("users_role", "desc")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_role",
        sa.Column("desc", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_users_role_name"), table_name="users_role")
    op.create_index("ix_users_role_desc", "users_role", ["desc"], unique=False)
    op.drop_column("users_role", "name")
    # ### end Alembic commands ###
