"""Creates user role

Revision ID: dae99ac4f75d
Revises: b5ef35c28bbd
Create Date: 2023-04-17 14:20:18.466331

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "dae99ac4f75d"
down_revision = "b5ef35c28bbd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("desc", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_role_desc"), "users_role", ["desc"], unique=False)
    op.create_index(op.f("ix_users_role_id"), "users_role", ["id"], unique=False)
    op.add_column("users", sa.Column("role_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_users_role_id", "users", "users_role", ["role_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_role_id", "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    op.drop_index(op.f("ix_users_role_id"), table_name="users_role")
    op.drop_index(op.f("ix_users_role_desc"), table_name="users_role")
    op.drop_table("users_role")
    # ### end Alembic commands ###
