FROM golang:1.20-alpine

RUN go install github.com/cortesi/modd/cmd/modd@latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /app/server /app/cmd/server

CMD [ "/app/server" ]
