FROM golang:1.20-bullseye

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .


RUN :\
  && apt-get update \
  && apt-get install -y cron \
  && :

RUN go build -o output/daemon ./cmd/daemon

COPY docker/crontab /etc/cron.d/crontab

COPY docker/daemon-entry-point.sh .

# RUN crontab /etc/cron.d/crontab

CMD ["/app/daemon-entry-point.sh"]
