name: Deploy

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_INSTANCE_SG_ID: ${{ secrets.AWS_SG_INSTANCE }}
      VERSION: ${{ github.sha }}
      APP_HOME: /home/ubuntu/app
    steps:
    - uses: twingate/github-action@v1
      with:
        service-key: ${{ secrets.TWINGATE_GITHUB_KEY }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Bump docker-compose image versions
      run: |
        # You can customize this part to bump the versions as needed
        # Here's a simple example that updates the image tag to the commit SHA
        sed -i "s/:latest/:$VERSION/g" docker-compose.prod.yml

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/bake-action@v3
      with:
        push: true

    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST_PRIVATE_IP }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        source: "docker-compose.prod.yml"
        target: ${{ env.APP_HOME }}

    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.REMOTE_HOST_PRIVATE_IP }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd ${{ env.APP_HOME }}
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml up -d
