name: Deploy

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_INSTANCE_SG_ID: ${{ secrets.AWS_SG_INSTANCE }}
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: get runner ip address
      id: ip
      uses: haythem/public-ip@v1.3
    - name: whitelist runner ip address
      run: |
        aws ec2 authorize-security-group-ingress \
          --group-id $AWS_INSTANCE_SG_ID \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push nginx-conf
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:nginx-conf"
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/proxy:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:frontend"
        file: ./Dockerfile.prod
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/frontend:latest

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:backend"
        file: ./Dockerfile.api
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/backend:latest

    - name: Build and push daemon
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:backend"
        file: ./Dockerfile.daemon
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/daemon:latest

  update_production:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    steps:
    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd /home/ubuntu/erp-bot-crypto
          git pull
          docker compose pull
          docker compose down
          docker compose up -d

  cleanup:
    runs-on: ubuntu-latest
    needs: [build_and_deploy, update_production]
    steps:
    - name: revoke runner ip address
      if: ${{ always() }}
      run: |
        aws ec2 revoke-security-group-ingress \
          --group-id $AWS_INSTANCE_SG_ID \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32
