name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_INSTANCE_SG_ID: ${{ secrets.AWS_SG_INSTANCE }}
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: get runner ip address
      id: ip
      uses: haythem/public-ip@v1.2
    - name: whitelist runner ip address
      run: |
        aws ec2 authorize-security-group-ingress \
          --group-id $AWS_INSTANCE_SG_ID \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32






    # - name: Bump docker-compose image versions
    #   run: |
    #     # You can customize this part to bump the versions as needed
    #     # Here's a simple example that updates the image tag to the commit SHA
    #     export COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
    #     sed -i "s/:latest/:$COMMIT_SHA/g" docker-compose.yml
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push nginx-conf
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:nginx-conf"
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/proxy:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:frontend"
        file: ./Dockerfile.prod
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/frontend:latest

    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:backend"
        file: ./Dockerfile.api
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/backend:latest

    - name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:backend"
        file: ./Dockerfile.daemon
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/daemon:latest

    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd /home/ubuntu/erp-bot-crypto
          git pull
          export COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          sed -i "s/:latest/:$COMMIT_SHA/g" docker-compose.prod.yml
          docker-compose pull
          docker-compose down
          docker-compose up -d
    - name: revoke runner ip address
      run: |
        aws ec2 revoke-security-group-ingress \
          --group-id $AWS_INSTANCE_SG_ID \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32
